name: Build JSON module and Redis Server
description: |
  Build JSON module and Redis Server

inputs:
  sanitizer:
    type: string

runs:
  using: composite
  steps:
    - name: Build Redis
      shell: bash
      working-directory: redis
      run: |
        echo "::group::Build Redis"
        make -j `nproc`
        echo "REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/redis/src" >> $GITHUB_PATH
        export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
        redis-server --version
        echo "::endgroup::"
    - name: Build module
      shell: bash
      run: |
        echo ::group::Build module
          make -j `nproc`
        echo ::endgroup::
