name: Build and test RedisBloom
description: Build and test RedisBloom

inputs:
  redis-version:
    description: 'Redis version to build'
    required: true
    default: '7.4'

runs:
  using: composite
  steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Python dependencies
      shell: bash
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r tests/flow/requirements.txt
        python3 -m pip install -r .install/build_package_requirements.txt
    - name: Checkout Redis
      uses: actions/checkout@v3
      with:
        repository: 'redis/redis'
        ref: ${{ inputs.redis-version }}
        path: 'redis'
    - name: Build Redis
      shell: bash
      run: |
        cd redis && gmake -j `sysctl -n hw.logicalcpu`
        echo "REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/redis/src" >> $GITHUB_PATH
        export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
        redis-server --version
    - name: Build RedisBloom
      shell: bash
      run: |
        gmake -j `sysctl -n hw.logicalcpu`
    - name: Run tests
      shell: bash
      run: |
        source .venv/bin/activate
        gmake test
