name: Run pack module script

inputs:
  beta-version:
    description: 'Version suffix for beta builds (YYYYMMDD.HHMMSS.RUN_NUMBER format)'
    required: false

runs:
  using: composite
  steps:
    - name: Pack module
      shell: bash
      run: |
        if command -v scl_source &> /dev/null
        then
            . scl_source enable devtoolset-11 || true
        fi
        . venv/bin/activate
        export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
        git config --global --add safe.directory $GITHUB_WORKSPACE
          if [[ -n "${{ inputs.beta-version }}" ]]; then
            export BETA_VERSION="${{ inputs.beta-version }}"
          fi
        make pack BRANCH=$TAG_OR_BRANCH SHOW=1
