name: Run pack module script

runs:
  using: composite
  steps:
    - name: Pack module
      shell: bash
      run: |
        . venv/bin/activate
        export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
        git config --global --add safe.directory $GITHUB_WORKSPACE
        make pack BRANCH=$TAG_OR_BRANCH SHOW=1
