#!/usr/bin/env bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)
READIES=$ROOT/deps/readies
. $READIES/shibumi/defs

OP=""
[[ $NOP == 1 ]] && OP=echo

OS=`uname -s`
if [[ $OS == Linux ]]; then
	FBINFER_OS=linux64
elif [[ $OS == Darwin ]]; then
	$OP brew install infer
	exit 0
else
	eprint "Cannot determine OS"
	exit 1
fi

VERSION="${VERSION:-1.0.0}"
FNINFER_NAME="infer-${FBINFER_OS}-v${VERSION}"
FBINFER_ARCHIVE="${FNINFER_NAME}.tar.xz"

if [[ ! -d /opt/${FNINFER_NAME} ]]; then
	x_dir=$(mktemp -d /tmp/fbinfer.XXXXXX)
	cd $x_dir
	runn wget -q --no-check-certificate https://github.com/facebook/infer/releases/download/v$VERSION/${FBINFER_ARCHIVE}
	$OP mkdir -p /opt/${FNINFER_NAME}
	runn $SUDO tar -C /opt -xf ${FBINFER_ARCHIVE}
	cd /
	$OP rm -rf $x_dir
fi
if [[ -f /opt/${FNINFER_NAME}/bin/infer ]]; then
	runn $SUDO ln -sf /opt/${FNINFER_NAME}/bin/infer /usr/local/bin/infer
fi

