name: Pack the module and upload it to S3
description: Pack the module and upload it to S3

inputs:
  is_tag:
    description: "Is this a tag?"
    required: true
    default: 'false'
  tag_or_branch:
    description: 'Tag or branch name.'
    required: true

runs:
  using: composite
  steps:
    - name: Pack module
      shell: bash
      run: |
        source .venv/bin/activate
        gmake pack BRANCH=${{inputs.tag_or_branch}} SHOW=1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: "us-east-1"
    - name: Upload artifacts to S3
      shell: bash
      run: |
        source .venv/bin/activate
        # Upload script needs GNU du
        export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"

        mkdir -p bin
        ln -s ~/workspace/artifacts bin/artifacts
        if [[ "${{inputs.is_tag}}" == "false" ]]; then
          gmake upload-artifacts SHOW=1 VERBOSE=1
        else
          gmake upload-release SHOW=1 VERBOSE=1
        fi
