name: Run a Benchmark Flow

on:
  workflow_call:
    inputs:
      module_path:
        type: string
        default: bin/linux-x64-release/redisbloom.so
      triggering_env:
        type: string
        default: "circleci" # TODO: change to "github-actions" when ready on grafana

jobs:
  benchmark-steps:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      run: make

    - name: Install terraform
      env:
        VERSION: 0.14.8
      run: ./deps/readies/bin/getterraform
    
    - name: install benchmark dependencies
      run: pip3 install -r ./tests/benchmarks/requirements.txt
    
    - name: Run benchmarks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PERFORMANCE_EC2_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PERFORMANCE_EC2_SECRET_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.PERFORMANCE_EC2_REGION }}
        EC2_PRIVATE_PEM: ${{ secrets.PERFORMANCE_EC2_PRIVATE_PEM }}
      run: |
        cd tests/benchmarks
        redisbench-admin run-remote \
          --required-module bf \
          --module_path ../../${{ inputs.module_path }} \
          --github_actor ${{ github.triggering_actor }} \
          --github_repo ${{ github.event.repository.name }} \
          --github_org ${{ github.repository_owner }} \
          --github_branch ${{ github.head_ref || github.ref_name }} \
          --continue-on-module-check-error \
          --upload_results_s3 \
          --triggering_env ${{ inputs.triggering_env }} \
          --fail_fast \
          --push_results_redistimeseries \
          --redistimeseries_host ${{ secrets.PERFORMANCE_RTS_HOST }} \
          --redistimeseries_port ${{ secrets.PERFORMANCE_RTS_PORT }} \
          --redistimeseries_pass '${{ secrets.PERFORMANCE_RTS_AUTH }}'
  
    - name: Generate Pull Request Performance info
      env:
        PERFORMANCE_GH_TOKEN: ${{ secrets.PERFORMANCE_GH_TOKEN }}
        PERFORMANCE_WH_TOKEN: ${{ secrets.PERFORMANCE_WH_TOKEN }}
      if: github.event.number
      run: |
        redisbench-admin compare  \
          --defaults_filename ./tests/benchmarks/defaults.yml \
          --comparison-branch ${{ github.head_ref || github.ref_name }} \
          --auto-approve \
          --pull-request ${{github.event.number}} \
          --redistimeseries_host ${{ secrets.PERFORMANCE_RTS_HOST }} \
          --redistimeseries_port ${{ secrets.PERFORMANCE_RTS_PORT }} \
          --redistimeseries_pass '${{ secrets.PERFORMANCE_RTS_AUTH }}'
