name: Branch Merge benchmarks

on:
  push:
      paths-ignore:
          - '.circleci/**'
          - 'docs/**'
          - '*.md'
      branches:
          - main
          - master
          - '[0-9]+.[0-9]+.[0-9]+'
          - '[0-9]+.[0-9]+'
      tags:
          - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
          - 'v[0-9]+.[0-9]+.[0-9]+-m[0-9]+'
          - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  run-benchmarks:
    uses: ./.github/workflows/benchmark-runner.yml
    secrets: inherit
    with:
      extended: true
