name: Check if needs trigger CI benchmark

on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  haslabel:
    name: analyse labels
    runs-on: ubuntu-latest
    outputs:
      benchmark: ${{ steps.haslabel.outputs.labeled-run-benchmark }}
    steps:
      - uses: actions/checkout@v2
      - name: Labeled with run-benchmark
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'run-benchmark'
  perf-ci:
    name: Trigger CI benchmarks from label
    needs: haslabel
    uses: ./.github/workflows/benchmark-runner.yml
    secrets: inherit
